name: bitsdojo_window_v3
description: A package to help with creating custom windows with Flutter desktop (custom border, titlebar and minimize/maximize/close buttons) and common desktop window operations (show/hide/position on screen) for Windows and macOS
version: 3.0.0
homepage: https://www.bitsdojo.com
repository: https://github.com/DartGit-dev/bitsdojo_window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: bitsdojo_window_windows_v3
      macos:
        default_package: bitsdojo_window_macos_v3
      linux:
        default_package: bitsdojo_window_linux_v3

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface_v3:
    ^3.0.0
    # path: ../bitsdojo_window_platform_interface_v3
  bitsdojo_window_windows_v3:
    ^3.0.0
    # path: ../bitsdojo_window_windows_v3
  bitsdojo_window_macos_v3:
    ^3.0.0
    # path: ../bitsdojo_window_macos_v3
  bitsdojo_window_linux_v3:
    ^3.0.0
    # path: ../bitsdojo_window_linux_v3
