name: bitsdojo_window
description: A package to help with creating custom windows with Flutter desktop (custom border, titlebar and minimize/maximize/close buttons) and common desktop window operations (show/hide/position on screen) for Windows and macOS
version: 0.1.3
homepage: https://www.bitsdojo.com
repository: https://github.com/bitsdojo/bitsdojo_window

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: bitsdojo_window_windows
      macos:
        default_package: bitsdojo_window_macos
      linux:
        default_package: bitsdojo_window_linux

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface: ^0.1.2
    #path: ../bitsdojo_window_platform_interface
  bitsdojo_window_windows: ^0.1.3
    #path: ../bitsdojo_window_windows
  bitsdojo_window_macos: ^0.1.3
    #path: ../bitsdojo_window_macos
  bitsdojo_window_linux: ^0.1.3
    #path: ../bitsdojo_window_linux
