name: bitsdojo_window_linux_v3
description: Linux implementation of the bitsdojo_window plugin.
version: 3.0.1
homepage: https://www.bitsdojo.com
repository: https://github.com/DartGit-dev/bitsdojo_window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface_v3:
    ^3.0.0
    #path: ../bitsdojo_window_platform_interface_v3
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: BitsdojoWindowPlugin
